import { useEffect, useMemo, useState } from "react";
import type { PluginPageProps } from "@paperclipai/plugin-sdk/ui";

type LibraryItemKind = "work_product" | "document" | "attachment";

interface LibraryItem {
  kind: LibraryItemKind;
  id: string;
  title: string;
  subtitle: string | null;
  issueId: string;
  issueTitle: string | null;
  issueIdentifier: string | null;
  url: string | null;
  contentType: string | null;
  byteSize: number | null;
  updatedAt: string;
  createdAt: string;
  extra: Record<string, unknown>;
}

interface LibraryResponse {
  items: LibraryItem[];
}

const KIND_LABELS: Record<LibraryItemKind, string> = {
  work_product: "Work product",
  document: "Document",
  attachment: "Attachment",
};

const KIND_FILTERS: Array<{ value: "all" | LibraryItemKind; label: string }> = [
  { value: "all", label: "All" },
  { value: "work_product", label: "Work products" },
  { value: "document", label: "Documents" },
  { value: "attachment", label: "Attachments" },
];

function formatBytes(n: number | null): string {
  if (n === null || !Number.isFinite(n)) return "";
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  if (n < 1024 * 1024 * 1024) return `${(n / (1024 * 1024)).toFixed(1)} MB`;
  return `${(n / (1024 * 1024 * 1024)).toFixed(1)} GB`;
}

function formatDate(iso: string): string {
  try {
    const d = new Date(iso);
    const now = Date.now();
    const diff = (now - d.getTime()) / 1000;
    if (diff < 60) return "just now";
    if (diff < 3600) return `${Math.floor(diff / 60)}m ago`;
    if (diff < 86400) return `${Math.floor(diff / 3600)}h ago`;
    if (diff < 86400 * 7) return `${Math.floor(diff / 86400)}d ago`;
    return d.toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" });
  } catch {
    return iso;
  }
}

export function LibraryPage({ context }: PluginPageProps) {
  const { companyId, companySlug } = context;
  const [items, setItems] = useState<LibraryItem[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [kindFilter, setKindFilter] = useState<"all" | LibraryItemKind>("all");
  const [query, setQuery] = useState("");

  useEffect(() => {
    if (!companyId) return;
    let cancelled = false;
    setError(null);
    setItems(null);
    fetch(`/api/companies/${encodeURIComponent(companyId)}/library?limit=500`, {
      credentials: "include",
    })
      .then(async (response) => {
        if (!response.ok) {
          throw new Error(`HTTP ${response.status}: ${response.statusText}`);
        }
        return response.json() as Promise<LibraryResponse>;
      })
      .then((data) => {
        if (cancelled) return;
        setItems(data.items);
      })
      .catch((err: unknown) => {
        if (cancelled) return;
        setError(err instanceof Error ? err.message : "Failed to load library");
      });
    return () => {
      cancelled = true;
    };
  }, [companyId]);

  const filtered = useMemo(() => {
    if (!items) return [];
    const q = query.trim().toLowerCase();
    return items.filter((item) => {
      if (kindFilter !== "all" && item.kind !== kindFilter) return false;
      if (!q) return true;
      return (
        item.title.toLowerCase().includes(q)
        || (item.subtitle ?? "").toLowerCase().includes(q)
        || (item.issueTitle ?? "").toLowerCase().includes(q)
        || (item.issueIdentifier ?? "").toLowerCase().includes(q)
      );
    });
  }, [items, kindFilter, query]);

  const counts = useMemo(() => {
    const result: Record<LibraryItemKind, number> = {
      work_product: 0,
      document: 0,
      attachment: 0,
    };
    for (const item of items ?? []) {
      result[item.kind] += 1;
    }
    return result;
  }, [items]);

  if (!companyId) {
    return (
      <div style={{ padding: "16px", color: "var(--muted-foreground, #64748b)" }}>
        Select a company to view its Library.
      </div>
    );
  }

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
      <header>
        <h1 style={{ margin: 0, fontSize: "18px", fontWeight: 600 }}>Library</h1>
        <p style={{ margin: "4px 0 0", fontSize: "12px", color: "var(--muted-foreground, #64748b)" }}>
          Every file, document, and work product generated by tickets in this company.
        </p>
      </header>

      <div
        style={{
          display: "flex",
          flexWrap: "wrap",
          alignItems: "center",
          gap: "8px",
          fontSize: "12px",
        }}
      >
        {KIND_FILTERS.map((option) => {
          const selected = option.value === kindFilter;
          const count =
            option.value === "all"
              ? (items?.length ?? 0)
              : counts[option.value];
          return (
            <button
              key={option.value}
              type="button"
              onClick={() => setKindFilter(option.value)}
              style={{
                padding: "4px 10px",
                borderRadius: "999px",
                border: "1px solid var(--border, #e2e8f0)",
                background: selected ? "var(--accent, #0f172a)" : "transparent",
                color: selected ? "var(--accent-foreground, #ffffff)" : "inherit",
                cursor: "pointer",
                fontSize: "12px",
              }}
            >
              {option.label} <span style={{ opacity: 0.7 }}>· {count}</span>
            </button>
          );
        })}
        <input
          type="search"
          value={query}
          onChange={(event) => setQuery(event.target.value)}
          placeholder="Search title, issue, contents…"
          style={{
            marginLeft: "auto",
            padding: "6px 10px",
            borderRadius: "6px",
            border: "1px solid var(--border, #e2e8f0)",
            background: "transparent",
            fontSize: "12px",
            minWidth: "220px",
          }}
        />
      </div>

      {error && (
        <div
          style={{
            padding: "10px 12px",
            borderRadius: "6px",
            background: "var(--destructive-foreground, #fef2f2)",
            color: "var(--destructive, #b91c1c)",
            fontSize: "13px",
          }}
        >
          {error}
        </div>
      )}

      {!items && !error && (
        <div style={{ fontSize: "13px", color: "var(--muted-foreground, #64748b)" }}>
          Loading…
        </div>
      )}

      {items && filtered.length === 0 && !error && (
        <div
          style={{
            padding: "24px",
            textAlign: "center",
            fontSize: "13px",
            color: "var(--muted-foreground, #64748b)",
            border: "1px dashed var(--border, #e2e8f0)",
            borderRadius: "8px",
          }}
        >
          {items.length === 0
            ? "Nothing here yet. Work products, issue documents, and file attachments will show up as your agents generate them."
            : "No matches."}
        </div>
      )}

      {filtered.length > 0 && (
        <LibraryTable items={filtered} companySlug={companySlug} />
      )}
    </div>
  );
}

function LibraryTable({
  items,
  companySlug,
}: {
  items: LibraryItem[];
  companySlug: string | null;
}) {
  return (
    <div
      style={{
        border: "1px solid var(--border, #e2e8f0)",
        borderRadius: "8px",
        overflow: "hidden",
      }}
    >
      <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "13px" }}>
        <thead>
          <tr style={{ background: "var(--muted, #f8fafc)", textAlign: "left" }}>
            <th style={thStyle}>Title</th>
            <th style={thStyle}>Kind</th>
            <th style={thStyle}>Issue</th>
            <th style={thStyle}>Size</th>
            <th style={thStyle}>Updated</th>
          </tr>
        </thead>
        <tbody>
          {items.map((item) => (
            <LibraryRow key={`${item.kind}:${item.id}`} item={item} companySlug={companySlug} />
          ))}
        </tbody>
      </table>
    </div>
  );
}

function LibraryRow({
  item,
  companySlug,
}: {
  item: LibraryItem;
  companySlug: string | null;
}) {
  const issueHref = companySlug
    ? `/${companySlug}/issues/${item.issueId}`
    : null;
  const titleNode = item.url ? (
    <a
      href={item.url}
      target={item.kind === "work_product" ? "_blank" : undefined}
      rel="noreferrer"
      style={{ color: "inherit", textDecoration: "none", fontWeight: 500 }}
    >
      {item.title}
    </a>
  ) : (
    <span style={{ fontWeight: 500 }}>{item.title}</span>
  );

  return (
    <tr style={{ borderTop: "1px solid var(--border, #e2e8f0)" }}>
      <td style={tdStyle}>
        <div style={{ display: "flex", flexDirection: "column", gap: "2px" }}>
          {titleNode}
          {item.subtitle && (
            <span
              style={{
                fontSize: "11px",
                color: "var(--muted-foreground, #64748b)",
                overflow: "hidden",
                textOverflow: "ellipsis",
                whiteSpace: "nowrap",
                maxWidth: "420px",
              }}
            >
              {item.subtitle}
            </span>
          )}
        </div>
      </td>
      <td style={tdStyle}>
        <span
          style={{
            display: "inline-block",
            padding: "2px 8px",
            borderRadius: "999px",
            background: "var(--muted, #f1f5f9)",
            fontSize: "11px",
            textTransform: "uppercase",
            letterSpacing: "0.04em",
          }}
        >
          {KIND_LABELS[item.kind]}
        </span>
      </td>
      <td style={tdStyle}>
        {issueHref ? (
          <a href={issueHref} style={{ color: "inherit" }}>
            {item.issueIdentifier ?? item.issueTitle ?? item.issueId.slice(0, 8)}
          </a>
        ) : (
          item.issueIdentifier ?? item.issueTitle ?? item.issueId.slice(0, 8)
        )}
      </td>
      <td style={tdStyle}>{formatBytes(item.byteSize)}</td>
      <td style={{ ...tdStyle, color: "var(--muted-foreground, #64748b)", whiteSpace: "nowrap" }}>
        {formatDate(item.updatedAt)}
      </td>
    </tr>
  );
}

const thStyle: React.CSSProperties = {
  padding: "8px 12px",
  fontSize: "11px",
  fontWeight: 600,
  textTransform: "uppercase",
  letterSpacing: "0.04em",
  color: "var(--muted-foreground, #64748b)",
};

const tdStyle: React.CSSProperties = {
  padding: "10px 12px",
  verticalAlign: "top",
};
