import type { PaperclipPluginManifestV1 } from "@paperclipai/plugin-sdk";

const PLUGIN_ID = "paperclip.library";
const LIBRARY_PAGE_SLOT_ID = "library-page";
const LIBRARY_SIDEBAR_SLOT_ID = "library-sidebar";

/**
 * Library plugin — a company-scoped page that aggregates everything
 * file-like generated by tickets: work products, versioned issue
 * documents, and file attachments. Available at `/:companySlug/library`.
 */
const manifest: PaperclipPluginManifestV1 = {
  id: PLUGIN_ID,
  apiVersion: 1,
  version: "0.1.0",
  displayName: "Library",
  description: "Central company-scoped view of every file, document, and work product generated by tickets.",
  author: "Paperclip",
  categories: ["ui", "workspace"],
  capabilities: ["ui.page.register", "ui.sidebar.register", "companies.read", "issues.read"],
  entrypoints: {
    worker: "./dist/worker.js",
    ui: "./dist/ui",
  },
  ui: {
    slots: [
      {
        type: "page",
        id: LIBRARY_PAGE_SLOT_ID,
        displayName: "Library",
        exportName: "LibraryPage",
        routePath: "library",
        order: 20,
      },
      {
        type: "sidebar",
        id: LIBRARY_SIDEBAR_SLOT_ID,
        displayName: "Library",
        exportName: "LibrarySidebarLink",
        order: 20,
      },
    ],
  },
};

export default manifest;
